### Login (Get JWT)
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "j@d.com",
  "password": "12Az!3456"
}

###

### Create User
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@d.com",
  "password": "12Az!3456"
}

### Get All Users (Requires Auth)
GET http://localhost:3000/users
Authorization: Bearer <token>

### Get One User
GET http://localhost:3000/user/3
Authorization: Bearer <token>

### Update User
PATCH http://localhost:3000/user/1
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Jane Doe"
}

### Delete User
DELETE http://localhost:3000/user/2
Authorization: Bearer <token>
