services:
  backend:
    image: node:18-alpine
    working_dir: /server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server                    # Mount the backend folder
      - /server/node_modules              # Internal node_modules
    environment:
      - JWT_SECRET=secret
    command: sh -c "npm install && node server.js"

  frontend:
    image: node:18-alpine
    working_dir: /client
    ports:
      - "4200:4200"
    volumes:
      - ./client/frontend:/client               # Mount the frontend folder
      - /client/node_modules            # Internal node_modules
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    depends_on:
      - backend